// Generated by gencpp from file speak_listen/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SPEAK_LISTEN_MESSAGE_ADDTWOINTS_H
#define SPEAK_LISTEN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <speak_listen/AddTwoIntsRequest.h>
#include <speak_listen/AddTwoIntsResponse.h>


namespace speak_listen
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace speak_listen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speak_listen::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::speak_listen::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::speak_listen::AddTwoInts > {
  static const char* value()
  {
    return "speak_listen/AddTwoInts";
  }

  static const char* value(const ::speak_listen::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::speak_listen::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::speak_listen::AddTwoInts >
template<>
struct MD5Sum< ::speak_listen::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speak_listen::AddTwoInts >::value();
  }
  static const char* value(const ::speak_listen::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speak_listen::AddTwoIntsRequest> should match
// service_traits::DataType< ::speak_listen::AddTwoInts >
template<>
struct DataType< ::speak_listen::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::speak_listen::AddTwoInts >::value();
  }
  static const char* value(const ::speak_listen::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speak_listen::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::speak_listen::AddTwoInts >
template<>
struct MD5Sum< ::speak_listen::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speak_listen::AddTwoInts >::value();
  }
  static const char* value(const ::speak_listen::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speak_listen::AddTwoIntsResponse> should match
// service_traits::DataType< ::speak_listen::AddTwoInts >
template<>
struct DataType< ::speak_listen::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::speak_listen::AddTwoInts >::value();
  }
  static const char* value(const ::speak_listen::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEAK_LISTEN_MESSAGE_ADDTWOINTS_H
